Scientific Python for Programmers (21/2/2024) (#15)
* README: introduced topics under spp heading & updated the survey

* spp: corrected the structure

* spp: adopted the uniformity

* spp: typo

* spp: ValueError: invalid literal for int() with base 10:

* spp: AttributeError: 'DataFrame' object has no attribute 'append'

* spp: updated the data/inflammation-13.csv as per inflammation.xlsx

* spp: updated pandas' plot example

* spp: matched exercices with solutions

* spp: typo2

* spp: ordered and homogenized min, mean, max

* spp: final cosmatic bits